---
title: "&#39;Throw&#39; statement cannot omit operand outside a &#39;Catch&#39; statement or inside a &#39;Finally&#39; statement"
ms.date: 07/20/2015
f1_keywords: 
  - "vbc30666"
  - "bc30666"
helpviewer_keywords: 
  - "BC30666"
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
---
# &#39;Throw&#39; statement cannot omit operand outside a &#39;Catch&#39; statement or inside a &#39;Finally&#39; statement
`Throw` statements outside of `Catch` statement must supply the name of an exception object.  
  
 **Error ID:** BC30666  
  
## To correct this error  
  
1.  Specify the name of an exception object derived from `System.Exception`.  
  
2.  Restructure your code so that the `Throw` statement is inside a `Catch` block.  
  
## See Also  
 [Throw Statement](../../visual-basic/language-reference/statements/throw-statement.md)  
 [Try...Catch...Finally Statement](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [Exception Class in Visual Basic](https://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)  
 [Exception and Error Handling in Visual Basic](https://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
